#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: frontend-router
  namespace: abshop
spec:
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  routes:
    - name: frontend-v2a
      priority: 10
      httpRoute:
        match:
          prefix: /
          headers:
            - name: Cookie
              match:
                regex: ".*app_version=v2a.*"
        action:
          weightedTargets:
            - virtualNodeRef:
                name: frontend-v2a
              weight: 1
    - name: frontend-v2b
      priority: 11
      httpRoute:
        match:
          prefix: /
          headers:
            - name: Cookie
              match:
                regex: ".*app_version=v2b.*"
        action:
          weightedTargets:
            - virtualNodeRef:
                name: frontend-v2b
              weight: 1
    - name: frontend-v2
      priority: 20
      httpRoute:
        match:
          prefix: /
          headers:
            - name: User-Agent
              match:
                regex: ".*Chrome.*"
        action:
          weightedTargets:
            - virtualNodeRef:
                name: frontend-v1
              weight: 8
            - virtualNodeRef:
                name: frontend-v2a
              weight: 1
            - virtualNodeRef:
                name: frontend-v2b
              weight: 1
    - name: frontend-v1
      priority: 100
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: frontend-v1
              weight: 1